trigger_item: CLOCK # Used for age lock/unlock
silence_item: BELL # Used for silencing/unsilencing

success_message: '&aBaby is now locked!'
success_particle: VILLAGER_HAPPY
lock_sound: ENTITY_EXPERIENCE_ORB_PICKUP
unlock_message: '&eBaby is now unlocked!'
unlock_particle: VILLAGER_HAPPY
unlock_sound: ENTITY_EXPERIENCE_ORB_PICKUP
permission_message: '&cYou can''t do that here!'
permission_sound: BLOCK_NOTE_BLOCK_BASS
sound_volume: 0.2
sound_pitch: 1.0

silence_message: '&7Mob silenced!'
silence_particle: CLOUD
silence_sound: BLOCK_NOTE_BLOCK_PLING
unsilence_message: '&aMob unsilenced!'
unsilence_particle: NOTE
unsilence_sound: ENTITY_EXPERIENCE_ORB_PICKUP
silence_permission_message: '&cYou can''t silence this mob!'
silence_permission_sound: BLOCK_NOTE_BLOCK_BASS
silence_sound_volume: 0.2
silence_sound_pitch: 1.0

runcommandall_command: mycommand $player

debug: false

reverse_dropper:
  collision:
    required_hits: 1
    window_ms: 1500
    debounce_ms: 250
  starts:
    icecreamfloater:
      world: Nest_the_end
      x: 290
      y: 16.0
      z: -67
      yaw: 85.19858
      pitch: -90.0
  regions_whitelist:
    - icecreamfloater

resource:
  world: "Resource"
  message: "&8» &cWARNING: This world is reset monthly, and claims can not be made here. Want to enter the Permanent world? Choose the Overworld by opening the '/rtp' menu."
  cooldown_ms: 8000
  bypass_permission: "perch.resourceworld.bypass"
  max_hours: 12
