name: PerchEntityUtils
version: '1.0.0'
main: me.perch.entityutils.Main
api-version: 1.20
authors: [ KayaLambrex ]

commands:
  runcommandall:
    description: Runs a configured command on all online players
    usage: /runcommandall
    permission: perchentityutils.runcommandall
    permission-message: You do not have permission to use this command.

permissions:
  perchentityutils.runcommandall:
    description: Allows use of /runcommandall
    default: op